/*
jquery utils EZG v1.035
accordion:  based on jQuery Ui Accordion plugin (http://www.opensource.org/licenses/mit-license.php)
cluetip:   based on jQuery clueTip plugin  (http://www.opensource.org/licenses/mit-license.php)
jQuery Nivo Slider v3.0.1, http://nivo.dev7studios.com, Copyright 2012, Dev7studios (http://www.opensource.org/licenses/mit-license.php)
reflection.js for jQuery v1.1 (c) 2006-2011 Christophe Beyls <http://www.digitalia.be> MIT-style license.
easyAccordion 0.1 Copyright (c) 2010 Andrea Cima Serniotti (http://www.madeincima.eu) Dual licensed under the MIT (MIT-LICENSE.txt) and GPL (GPL-LICENSE.txt) licenses.
parseQuery Copyright (c) 2008 Michael Manning (http://actingthemaggot.com) Dual licensed under the MIT (MIT-LICENSE.txt) and GPL (GPL-LICENSE.txt) licenses.
other scripts : http://www.ezgenerator.com  Copyright (c) 2004-2013 Image-line
*/
jQuery.fn.getRandomArea=function(){var b=Math.floor(Math.random()*this.length);this.each(function(c,f){c!=b?$(f).empty():$(f).css({display:"block"})});return jQuery(this[b])};jQuery.fn.linkAreaToMenu=function(){this.each(function(b,c){cl=$(c).attr("class");var f=cl.split(" ");$("li#"+f[1]).mouseenter(function(){$("."+f[0]).hide();$("."+f[0]+"."+f[1]).show()})});return 1};$(document).ready(function(){$(".w_button a").mousedown(function(){$(this).parent().addClass("active")}).mouseup(function(){$(this).parent().removeClass("active")})});
jQuery.fn.updateMenu=function(b){url=(b?"":"../")+"documents/centraladmin.php";$.get(url,{process:"up"},function(b){-1<b.indexOf("<")||("none"!=b&&$(".login_form_logged").show().prev().hide(),"all"==b?$(".hidden").removeClass("hidden"):$.each(b.split("|"),function(b,c){$("#mi"+c).removeClass("hidden")}))});return!0};function setCookie(b,c,f,k){var e=new Date;e.setDate(e.getDate()+f);c=escape(c)+(null==f?"":"; expires="+e.toUTCString())+(null==k?"":"; path="+k);document.cookie=b+"="+c}
function getCookie(b){var c,f,k,e=document.cookie.split(";");for(c=0;c<e.length;c++)if(f=e[c].substr(0,e[c].indexOf("=")),k=e[c].substr(e[c].indexOf("=")+1),f=f.replace(/^\s+|\s+$/g,""),f==b)return unescape(k)}
jQuery.parseQuery=function(b,c){var f="string"===typeof b?b:window.location.search,k={f:function(b){return unescape(b).replace(/\+/g," ")}},k=jQuery.extend({},k,"object"===typeof b&&"undefined"===typeof c?b:c),e={};jQuery.each(f.match(/^\??(.*)$/)[1].split("&"),function(b,c){c=c.split("=");c[1]=k.f(c[1]);e[c[0]]=e[c[0]]?e[c[0]]instanceof Array?(e[c[0]].push(c[1]),e[c[0]]):[e[c[0]],c[1]]:c[1]});return e};
(function(b){b.fn.insertAtCaret=function(b){return this.each(function(){if(document.selection)this.focus(),sel=document.selection.createRange(),sel.text=b,this.focus();else if(this.selectionStart||"0"==this.selectionStart){var f=this.selectionStart,k=this.selectionEnd,e=this.scrollTop;this.value=this.value.substring(0,f)+b+this.value.substring(k,this.value.length);this.focus();this.selectionStart=f+b.length;this.selectionEnd=f+b.length;this.scrollTop=e}else this.value+=b,this.focus()})}})(jQuery);
(function(b){b.fn.autogrow=function(){this.filter("textarea").each(function(){var c=b(this),f=20<c.height()?c.height():20;c.css("lineHeight");var k=b("<div></div>").css({position:"absolute",top:-1E4,left:-1E4,width:b(this).width()-parseInt(c.css("paddingLeft"))-parseInt(c.css("paddingRight")),fontSize:c.css("fontSize"),fontFamily:c.css("fontFamily"),lineHeight:c.css("lineHeight"),resize:"none"}).appendTo(document.body),c=function(){var c=this.value.replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/&/g,
"&amp;").replace(/\n$/,"<br/>&nbsp;").replace(/\n/g,"<br/>").replace(/ {2,}/g,function(b){for(var c=0,e="";c<b.length-1;c++)e+="&nbsp;";return e+" "});k.html(c);b(this).css("height",Math.max(k.height()+1,f))};b(this).change(c).keyup(c).keydown(c);c.apply(this)});return this}})(jQuery);
(function(b){b.fn.pmeter=function(){return this.each(function(){var c=b(this).attr("rel");"undefined"==c&&(c="");b(".out_pass_div"+c).css("width",b(this).width());b(this).keyup(function(){var f;f=b(this).val();f=null!==f.match(/^.{1,7}$/)?1:null!==f.match(/(?=^.{8,}$)((?=.*\d)|(?=.*\W+))(?![.\n])(?=.*[A-Z])(?=.*[a-z]).*$/)?5:null!==f.match(/^.{12,}$/)?5:null!==f.match(/(?=^.{8,}$)(?=.*\d)(?![.\n])(?=.*[a-zA-Z]).*$/)?4:null!==f.match(/^[^0-9]{8,11}$/)?3:null!==f.match(/^[0-9]{8,}$/)?2:-1;var k="",
e="";switch(f){case 5:k="#00FF00";e="strong";break;case 4:k="#00FFFF";e="good";break;case 3:k="#F5AC00";e="average";break;case 2:k="#FF0000";e="weak";break;case 1:k="#C0C0C0";e="short";break;default:k=""}b(".inn_pass_div"+c).css("width",30*f).css("background-color",k);b(".pass_progress_text"+c).hide();""!=e&&b("#pwdptext_"+e+c).show();"short"!=e&&b("#selfreg_password").text("")})})}})(jQuery);
(function(b){b.fn.rtable=function(c){c=b.extend({min:0,max:200,acolor:"#555555",asize:25},c||{});return this.each(function(){var f=this,k="transparent transparent "+c.acolor,e=c.acolor+" transparent transparent",g="0 "+c.asize+"px "+c.asize+"px",l=c.asize+"px "+c.asize+"px 0";b(f).animate({height:c.min});var m=b('<div class="rtable_arrow" style="cursor:pointer;border-color:'+e+";border-style:solid;border-width:"+l+';height:0;width:0"></div>').click(function(){nh=b(f).hasClass("max");b(f).animate({height:nh?
c.min:c.max}).toggleClass("max");nh?b(m).css({"border-color":e,"border-width":l}):b(m).css({"border-color":k,"border-width":g});b(m).toggleClass("up")});0<b("."+this.className+"_footer").length?b("."+this.className+"_footer").after(m):b(f).after(m)})}})(jQuery);
(function(b){b.fn.poll=function(c){c=b.extend({id:"",root:!0},c||{});return this.each(function(){function f(c){b(c).find(".bar").hide().end().fadeIn("slow",function(){b(this).find(".bar").each(function(){var c=b(this).attr("rel");b(this).css("width","0").show().animate({width:c+"%"},1E3)})})}var k=b(this).find(".loader"),e=c.root?"":"../",g=b(this).find(".pc");k.fadeIn();b.get(e+"ezg_data/poll.php",{poll_id:c.id},function(c){-1<c.indexOf("include_once")&&(c="Please upload to see poll working!");g.html(c);
g.before(g.find(".poll_title"));f(g);g.find("#pollform").submit(function(){""!=b(this).find("input[name=poll]:checked").val()&&(k.fadeIn(),b.post(e+"ezg_data/poll.php",b(this).serialize(),function(c){g.find("#formcontainer").fadeOut(100,function(){b(this).html(c);f(this);k.fadeOut()})}));return!1});k.fadeOut()})})}})(jQuery);
(function(b){b.fn.ranking=function(c){c=b.extend({cnt:5,url:"",rsw:80,numbers:!1},c||{});return this.each(function(){function f(e,g){d=b(e).prevUntil(".ranking_result").andSelf();g?d.addClass("ranking_star_active"):d.removeClass("ranking_star_active");c.numbers&&(g?d.css({opacity:0.7}):d.css({opacity:1}))}function k(e,g){pr=b('<div class="ranking_progress"></div>');wi=c.rsw*(g/c.cnt);c.numbers&&pr.css({opacity:0.7});pr.css({width:"0px"}).appendTo(e);pr.animate({width:wi+"px"})}var e=this;el_a=b(e).text();
var g=el_a.split(":"),l=g[0],m=g[1],r="0"==g[2],g="2"==g[2];b(e).empty();vo=b('<div class="ranking_result" rel="'+m+'"><span>'+l+"</span></div>");!r&&!g&&vo.empty().addClass("ranking_result_locked");vo.appendTo(e);for(i=0;i<c.cnt;i++){m=i+1;m=b('<div class="ranking_star" rel="'+m+'">'+(c.numbers?"<span>"+m+"</span>":"")+"</div>");if(!r||g)m.mouseover(function(){f(this,!0)}).mouseout(function(){f(this,!1)}),m.click(function(){b.get(c.url,{action:"ranking",entry_id:b(e).find(".ranking_result").attr("rel"),
value:this.getAttribute("rel")},function(c){b(e).find(".ranking_star").unbind("click");b(e).find(".ranking_result").empty().removeClass("ranking_result_locked").html("<span>"+c+"</span>");k(e,c)})});m.appendTo(e)}r&&k(e,l);b(".ranking").css("visibility","visible")})}})(jQuery);
(function(b){b.fn.resizeImg=function(c){c=b.extend({max:0},c||{});return this.each(function(){var c=this,k=b(c).attr("rel").split(","),e=parseInt(k[0],10),g=parseInt(k[1],10),l=2<k.length,m=b(c).width(),r=b(c).height(),k=b(c).outerWidth(!0),s=b(c).outerHeight(!0),n=b(c).css("float"),u=b(c).parent();mar=u.hasClass("rvps1")?";margin:0 auto;":u.hasClass("rvps2")?";margin-left:auto;":"";b(c).css({"z-index":3,position:"absolute",left:0});b(c).wrap('<div style="position:relative;z-index:1;width:'+k+"px;height:"+
s+"px;float:"+n+mar+'" />');b(c).hover(function(){var k=0,m=0;if(l){var n=b(c).parents("td");null!=n&&(cx=b(n).parent().children(),col=cx.index(b(n)),rx=b(n).parent().parent().children(),row=rx.index(b(n).parent()),col==cx.length-1&&(k=1),row==rx.length-1&&(m=1))}zz={width:e+"px",height:g+"px"};k&&(zz.left="-"+(e/2+1)+"px");m&&(zz.top="-"+(g/2+1)+"px");b(this).parent().css({"z-index":2});b(this).stop().animate(zz,400)},function(){b(this).stop().animate({width:m+"px",height:r+"px",left:"0px",top:"0px"},
100,function(){b(this).parent().css({"z-index":1})})})})}})(jQuery);
(function(b){b.fn.xzoom=function(c){c=b.extend({max:0},c||{});return this.each(function(){function c(e){o=b(k).offset();oX=o.left;oY=o.top;x=e.pageX-oX;y=e.pageY-oY;lx=x<l/2?0:x>r-l/2?r-l:x-l/2;ly=y<m/2?0:y>s-m/2?s-m:y-m/2}var k=this,e,g,l,m,r=b(k).width(),s=b(k).height(),n=b(k).outerWidth(!0),u=b(k).outerHeight(!0),q=b(k).css("float");p=b(k).parent();mar=p.hasClass("rvps1")?";margin:0 auto;":p.hasClass("rvps2")?";margin-left:auto;":"";b(k).wrap('<div style="position:relative;cursor:move;z-index:1;width:'+
n+"px;height:"+u+"px;float:"+q+mar+'" />');b("<img/>").attr("src",b(this).attr("src")).load(function(){g=this.width;e=g/r;l=Math.ceil(r/e);m=Math.ceil(s/e);mt=b('<div class="mt" style="position:absolute;top:0;left:0;z-index:100;background:url(.);width:'+r+"px;height:"+s+'px" />').mouseenter(function(e){xz=b('<div class="zoomed" style="position:absolute;display:none;width:'+r+"px;height:"+s+"px;left:"+(r+5)+"px;top:0px;background:url("+b(k).attr("src")+');" />');b(k).parent().append(xz);xz.fadeIn("fast");
c(e);b(k).parent().append('<div class="lens" style="position:absolute;top:'+ly+"px;left:"+lx+"px;width:"+(l-4)+"px;height:"+(m-4)+'px;background:white;border:2px solid #c0c0c0;opacity:0.3;z-index:5;" />')}).mousemove(function(g){c(g);pX=lx*e;pY=ly*e;b(k).parent().find(".lens").css({left:lx+"px",top:ly+"px"});b(k).parent().find(".zoomed").css("background-position",-pX+"px "+-pY+"px")}).mouseleave(function(){b(k).parent().find(".zoomed,.lens").remove()});b(k).parent().append(mt)})})}})(jQuery);
(function(b){b.fn.x_accordion=function(c){c=b.extend({active:0,autoHeight:!0,updAct:"click",collapsible:!1,transDur:400,header:"",tab:""},c||{});return this.each(function(){function f(e){-1<k&&b(m[k]).stop(!0,!0);if(0>k)b(m[e]).slideDown(c.transDur),k=e;else if(e!=k){b(l[k]).removeClass("active");var g=b(m[k]),f=b(m[e]),u=f.css("overflow"),q=0,v={},B={},A;A=f[0].style.width;f.width(parseInt(f.parent().width(),10)-parseInt(f.css("paddingLeft"),10)-parseInt(f.css("paddingRight"),10)-(parseInt(f.css("borderLeftWidth"),
10)||0)-(parseInt(f.css("borderRightWidth"),10)||0));b.each(["height","paddingTop","paddingBottom"],function(c,e){B[e]="hide";var g=(""+b.css(f[0],e)).match(/^([\d+-.]+)(.*)$/);v[e]={value:g[1],unit:g[2]||"px"}});f.css({height:0,overflow:"hidden"}).show();g.animate(B,{step:function(b,c){"height"==c.prop&&(q=0===c.end-c.start?0:(c.now-c.start)/(c.end-c.start));f[0].style[c.prop]=q*v[c.prop].value+v[c.prop].unit},duration:c.transDur,complete:function(){f.css("height","");f.css({width:A,overflow:u})}});
k=e}else b(m[e]).slideToggle(c.transDur),k=b(l[e]).hasClass("active")?-1:e;b(l[e]).toggleClass("active")}var k=-1;if(null!=b(this)){var e=b(this).attr("id"),g=b.parseQuery();null!=g[e]&&(c.active=parseInt(g[e])-1);var l=b(c.header),m=b(c.tab).css({display:"none",zoom:"1"});l.each(function(e){b(l[e]).bind(c.updAct,function(){f(e)})});-1<c.active&&f(c.active);this.slideTo=function(b){f(b)}}})}})(jQuery);
(function(b){b.fn.rssticker=function(c){c=b.extend({height:120,width:300,speed:1E3,autoplay:!0,delay:3E3,hor:!0,hidebtn:!0,count:1},c||{});return this.each(function(){function f(e,g){nh=0;g||(nh+=parseInt(b(u).find("li:last").attr("rel")));fi=e?b(u).children("li"):b(u).find("li:first").nextAll();b(fi).slice(0,g?c.count:c.count-1).each(function(){nh+=parseInt(b(this).attr("rel"))});return nh}function k(){clearTimeout(r);n&&(fi=b(u).find("li:first"),c.height=fi.height(),b(u).parent().animate({height:f(0,
1)},c.speed));b(u).find("li:first").animate(c.hor?{marginLeft:"-"+c.width+"px"}:{marginTop:"-"+c.height+"px"},c.speed,function(){b(this).detach().appendTo(u).css(c.hor?{marginLeft:v}:{marginTop:q});!m&&c.autoplay&&e(0)})}function e(b){clearTimeout(s);s=setTimeout(k,0==b?c.delay:b)}function g(){m=0;c.hidebtn&&b(u).find(".ctrls").hide();e(0)}function l(){m=1;b(u).find(".ctrls").show();clearTimeout(s)}var m=0,r=0,s=0,n="auto"==c.height,u=this;fi=b(u).find("li:first");var q=b(fi).css("marginTop"),v=b(fi).css("marginLeft");
n&&(b(u).find("li").each(function(){b(this).css("height",b(this).height())}),b(u).children("li").each(function(){b(this).attr("rel",b(this).outerHeight(!0))}),b(u).parent().css("height",f(1,1)));html='<div class="ctrls" style="position:absolute;'+(c.hidebtn?"display:none;":"")+'top:1px;right:1px;z-index:2"><input class="input1 ctrlup '+(c.hor?"hor":"")+'" type="button" value=""><input class="input1 ctrldo '+(c.hor?"hor":"")+'" type="button" value=""></div>';b(html).appendTo(u);b(u).find(".ctrlup").click(function(){k()});
b(u).find(".ctrldo").click(function(){clearTimeout(r);n&&(fi=b(u).find("li:last"),c.height=fi.height(),b(u).parent().animate({height:f(1,0)},c.speed));b(u).find("li:last").detach().prependTo(u).css(c.hor?{marginLeft:"-"+c.width+"px"}:{marginTop:"-"+c.height+"px"}).animate(c.hor?{marginLeft:v}:{marginTop:q},c.speed)});c.autoplay&&(navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/iPad/i)?b(u).bind("touchstart",function(){l()}).bind("touchend",function(){r=
setTimeout(g,3E3)}):b(u).hover(function(){l()},function(){g()}),e(0))})}})(jQuery);
(function(b){b.fn.mmenu_animation=function(c){c=b.extend({animSpeed:500},c||{});return this.each(function(){var f="ontouchstart"in window,k=/iPad|iPod|iPhone/.test(navigator.platform)&&"matchMedia"in window;if(f&&!k){var e=b(".mmenu.level1");b(e).attr("rel","0").bind("touchstart",function(){var c="0"==b(this).attr("rel");b(e).attr("rel",0);b(this).attr("rel",c?"1":"0");this.focus()}).bind("click",function(c){"1"==b(this).attr("rel")&&c.preventDefault()})}b(this).children("li").each(function(){var e=
b(this),k=e.children(".megamenu");0<k.length?b(k).children("ul:first").css({visibility:"visible",display:"block"}):k=e.children("ul:first");k&&(k.css({display:"none"}),e.mouseover(function(){k.hasClass("active")||k.addClass("active").stop(!0,!0).css({overflow:"hidden",height:"auto"}).animate({height:"show"},500,function(){k.css({overflow:"visible"})})}),e.mouseleave(function(){k.stop(!0,!0).hide().removeClass("active")}),b(k).children("li").each(function(e,g){var k=b(g),f=k.children("ul:first");f&&
(f.css({display:"none"}),k.mouseover(function(){f.hasClass("active")||f.addClass("active").animate({height:"show",width:"show"},c.animSpeed)}),k.mouseleave(function(){f.stop(!0,!0).hide().removeClass("active")}))}))})})}})(jQuery);
(function(b){b.fn.float_login=function(c){c=b.extend({animSpeed:500,d:0,op:!1,pos:"top",cook:!1,path:"",pageid:0},c||{});return this.each(function(){function f(){0<b(".logout_float").length&&b("#openLogin").hide()}function k(b){"left"==c.pos?b.animate({width:"show",marginLeft:"show",marginRight:"show",paddingLeft:"show",paddingRight:"show"},500):b.slideDown("slow")}var e=this;b("#openLogin").click(function(){c.cook&&setCookie("fl_open","1","1000","/");k(b(e))});b("#closeLogin").click(function(){c.cook&&
setCookie("fl_open","0","1000","/");var g=b(e);"left"==c.pos?g.animate({width:"hide",marginLeft:"hide",marginRight:"hide",paddingLeft:"hide",paddingRight:"hide"},500):g.slideUp("slow")});b("#toggle a").click(function(c){c.preventDefault();b("#toggle a").toggle()});b("#login_register,#forgot_pwd").click(function(c){c.preventDefault();b("#frm_login_error").empty();b.get(this.getAttribute("href"),function(c){b("#register_form").hide().html(c).slideDown(500)})});fr_l=b("#frm_login");null!=fr_l&&(fr_l.append('<input type="hidden" id="cc" name="cc" value="1"/>'),
fr_l.submit(function(c){c.preventDefault();b(".frmhint").empty();b("#div_frm_login").addClass("ajl").css("opacity","0.2").delay(500);b.post(fr_l.attr("action"),fr_l.serialize(),function(c){b("#div_frm_login").removeClass("ajl").css("opacity","1");if("1"==c)cc=b(".frm_login #cc"),cc.val("0"),fr_l.unbind("submit"),fr_l.submit(),cc.val("1");else if("0"==c.charAt(0)){errors=c.substring(1).split("|");for(i=0;i<errors.length;i+=2)b("#frm_login_"+errors[i]).append("<br />"+errors[i+1])}})}));if(c.cook){var g=
getCookie("fl_open");c.op=null==g||"1"==g}c.op&&(k(b(e)),b("#toggle a").toggle());c.d&&b(".logged_info").length?b.get(c.path+"documents/centraladmin.php",{process:"logged",vert:"left"==c.pos?1:0,pageid:c.pageid,nodw:1},function(c){-1==c.indexOf("<?php")&&(b(".logged_info").replaceWith(c),f())}):f()})}})(jQuery);
(function(b){b.fn.scrollbar=function(c){c=b.extend({slideInt:4E3,delay:4E3,navbar:!1,nb_numbers:!0,nb_hide:!1,rtl:!1,autoplay:!1,sc:!1,mw:1,tc:0,max:3,inf:0,scrollBymax:0,navw:80,cid:0,icont:"tc",iscroll:"t",cont:"g"},c||{});return this.each(function(){function f(e,g,k){g!=e&&q.css({"margin-left":-g});q.animate({"margin-left":-e},k?10:1E3);c.sc&&(p=100/(n.length-c.max),p*=c.cid,b(".ui-slider-handle").animate({left:p+"%"},1E3))}function k(e,g){el=b('<div id="'+e+'"></div>');c.tc&&el.append(g);b(m).append(el);
return el}function e(){l(r,0);B=setInterval(function(){l(r,0)},c.slideInt)}function g(e){c.inf||(ls=n.length-1,fr=100/ls,-1<e&&(c.cid=Math.floor(e/fr)),id=c.cid,0==id?b(J).hide():b(J).show(),id+c.max-1==ls?b(P).hide():b(P).show())}function l(e,k){c.navbar&&b(O[c.cid]).removeClass("active selected");k&&clearInterval(B);ls=n.length-1;inf=c.inf;id=c.cid;!inf&&(0==id&&0>e||0<e&&id+c.max>ls)?clearInterval(B):(v.stop(!0,!0),inf&&0>=id&&0>e?(c.cid=ls+1+e,inx=c.cid+A+r,sl=inx*u-D+I,ml=(inx+e)*u-D+I):inf&&
id+e>ls&&0<e?(c.cid=0,inx=A-r,sl=inx*u-D+I,ml=(inx+e)*u-D+I):(c.cid+=e,sl=ml=(c.cid+A)*u-D+I),f(ml,sl,0));c.navbar&&b(O[c.cid]).addClass("active selected");g(-1)}var m=this,r=c.scrollBymax?c.max:1;if(null!=b("#"+c.cont+"_tc")){var s=b.parseQuery();null!=s[c.cont]&&(c.cid=parseInt(s[c.cont])-1);var n=b("#"+c.cont+"_tc .tb"),u=n.first().outerWidth(!1),q=b("#"+c.cont+"_tc"),s=b(m).attr("id"),v=b("#"+c.cont+"_t"),B=0,A=0,J="#"+c.cont+"_prev",P="#"+c.cont+"_next",D=c.rtl?q.width():0,I=c.rtl?u:0;if(c.sc){v.append('<div class="sc-bar-wrap"><div class="sc-bar"></div></div>');
var E=b(".sc-bar").slider({slide:function(b,c){q.width()>v.width()?q.css("margin-left",Math.round(c.value/100*(v.width()-q.width()))+"px"):q.css("margin-left",0);g(c.value)}}),S=E.find(".ui-slider-handle").mousedown(function(){E.width(S.width())}).mouseup(function(){E.width("100%")}).wrap("<div class='ui-handle-helper-parent'></div>").parent();v.css("overflow","hidden");setTimeout(function(){q.width();v.width();q.width();E.find(".ui-slider-handle").css({width:100,"margin-left":-50});S.width("").width(E.width()-
100)},10)}n.length>c.max&&(k(s+"_next","&rsaquo;").bind("click",function(){l(r,1)}),k(s+"_prev","&lsaquo;").bind("click",function(){l(-r,1)}));if(c.navbar){el=b('<div class="'+c.cont+'_tc_navbar"></div>');n.each(function(e){a=b('<a class="'+c.cont+'_tc_navbar_item" style="outline:0" href="#">'+(c.nb_numbers?e+1:"&nbsp;")+"</a>").bind("click",function(b){b.preventDefault();l(e-c.cid,1)}).bind("mouseenter",function(){b(this).hasClass("selected")||b(this).addClass("active")}).bind("mouseleave",function(){b(this).hasClass("selected")||
b(this).removeClass("active")});b(el).append(a)});b(m).append(el);var O=b("."+c.cont+"_tc_navbar_item")}if(c.nb_hide){var R=b("."+c.cont+"_tc_navbar").hide();b("#"+c.cont).mouseenter(function(){b(R).animate({height:"show"},500)}).mouseleave(function(){b(R).animate({height:"hide"},500)})}-1==c.cid&&(c.cid=Math.floor(Math.random()*(n.length-1-0+1)+0));c.inf&&(q.append(n.slice(0,c.max).clone()),tl=n.length,q.prepend(n.slice(tl-c.max,tl).clone()),A=c.max);s=(c.cid+A)*u-D+I;f(s,s,1);c.navbar&&b(O[c.cid]).addClass("active selected");
g(-1);c.autoplay&&(B=setTimeout(e,c.delay),b(this).hover(function(){clearInterval(B)},function(){B=setTimeout(e,c.delay/2)}));this.slideTo=function(b){l(b,1)}}})}})(jQuery);
(function(b){b.fn.x_tabs=function(c){c=b.extend({dir:"h",s:"#",slideInt:4E3,transDur:700,updAct:"click",anim:!0,autoplay:!0,stop:!0,id:0,gmid:-1},c||{});return this.each(function(){function f(e){b(v[s]).stop(!0,!0);b(B[s]).removeClass("ct_act").addClass("ct");u&&b(q[s]).removeClass("ct_act").addClass("ct");b(v[s]).hide();c.anim&&b(v[s]).css("opacity",0);s=e;b(B[e]).removeClass("ct").addClass("ct_act");c.anim?b(v[e]).hide().css("display","block").animate({opacity:1},c.transDur,function(){var c=b(v[e]);
c.css("display","");b.support.opacity||c[0].style.removeAttribute("filter")}):b(v[e]).show();u&&b(q[e]).removeClass("ct").addClass("ct_act");c.gmid-1==e&&google.maps.event.trigger(map,"resize");if(ifr=b(v[e]).find(".ifr_ah"))he=b(ifr).contents().height(),b(ifr).attr("height",he)}var k=b(this);if(null!=k){var e=b(this).attr("id"),g="#"==c.s?"#"+e+"_":" .",l=b.parseQuery();null!=l[e]&&(c.id=parseInt(l[e])-1);var m=0,r=null,s=null;b(g+"di").css("display","block");var g="."+c.dir+"tab",l="."+c.dir+"div",
n=c.dir+"_tabs_on",u=c.dir="h";if(!k.hasClass(n)){k.addClass(n);if(u)var q=b("#"+e).find(".litab");var v=b("#"+e).find(l).hide();c.anim?v.css("opacity",0):0<c.id&&(s=0);var B=b("#"+e).find(g);f(c.id);c.autoplay&&(m=setInterval(function(){r=s;f(r+1>=v.length?0:r+1)},c.slideInt));B.each(function(e){b(B[e]).bind(c.updAct,function(){s!=e&&(c.autoplay&&clearInterval(m),f(e));c.stop&&clearInterval(m)})});B.bind("mousedown",function(){clearInterval(m)})}this.slideTo=function(b){c.autoplay&&clearInterval(m);
f(b)}}})}})(jQuery);
(function(b){b.fn.cluetip=function(c,f){var k,e,g,l,m,r;"object"==typeof c&&(f=c,c=null);if("destroy"==c)return this.removeData("thisInfo").unbind(".cluetip");if(null!=b(this))return this.each(function(){var s=this,n=b(this),u="TD"==this.tagName,q=b.extend({width:0,height:"auto",cluezIndex:97,positionBy:"auto",tipDelay:0,topOffset:15,leftOffset:15,attribute:"rel",titleAttribute:"title",escapeTitle:!1,showTitle:!1,className:"default",hoverClass:"",arrows:!1,dropShadow:!1,dropShadowSteps:3,sticky:!1,
mouseOutClose:!1,clickThrough:!0,closePosition:"bottom",closeText:"Close",fixed:!0,truncate:0,fx:{open:"fadeIn",openSpeed:"50"}},f||{},b.metadata?n.metadata():b.meta?n.data():{}),v=+q.cluezIndex;n.data("thisInfo",{title:s.title,zIndex:v});b("#"+q.className).length||(b(['<div id="'+q.className+'">','<div class="tip-top"></div><div class="tip"><h3 class="tip-title"></h3><div class="tip-text"></div></div><div id="cluetip-arrows" class="cluetip-arrows"></div></div>'].join("")).appendTo("body").hide(),
k=b("#"+q.className).css({position:"absolute"}),g=b(".tip").css({position:"relative",zIndex:v}),e=b(".tip-text"),l=b(".tip-title"),m=b("#cluetip-arrows"));var B=q.dropShadow?+q.dropShadowSteps:0;if(!r){r=b([]);for(var A=0;A<B;A++)r=r.add(b("<div></div>").css({zIndex:v-1,opacity:0.1,top:1+A,left:1+A}));r.css({position:"absolute",backgroundColor:"#000"}).prependTo(k)}var J=n.attr(q.attribute),P=q.className,D=parseInt(q.topOffset,10),I=parseInt(q.leftOffset,10),E,S,O=isNaN(parseInt(q.height,10))?"auto":
/\D/g.test(q.height)?q.height:q.height+"px",R,Q,N,T,V,U,M=parseInt(q.width,10),z=M+(parseInt(k.css("paddingLeft"),10)||0)+(parseInt(k.css("paddingRight"),10)||0)+B,K=b(this).parent().hasClass("thumb_mask")?b(this).parent().width():b(this).width(),F,C,G,L,H="title"!=q.attribute?n.attr(q.titleAttribute):"";void 0==H&&(H="");U=H.split("::");H=U.shift();q.escapeTitle&&(H=H.replace(/&/g,"&amp;").replace(/>/g,"&gt;").replace(/</g,"&lt;"));var X=function(c){k.addClass(P);if(q.truncate){var f=e.text().slice(0,
q.truncate)+"...";e.html(f)}b(".tip-text img").css("max-width",q.width-6);H?l.show().html(H):q.showTitle?l.show().html("&nbsp;"):l.hide();q.sticky&&(f=b('<div id="cluetip-close"><a href="#">'+q.closeText+"</a></div>"),"bottom"==q.closePosition?f.appendTo(e):"title"==q.closePosition?f.prependTo(l):f.prependTo(e),f.bind("click.cluetip",function(){W();return!1}),q.mouseOutClose?k.bind("mouseleave.cluetip",function(){W()}):k.unbind("mouseleave.cluetip"));f="";g.css({zIndex:n.data("thisInfo").zIndex,overflow:"auto"==
O?"visible":"auto",height:O});E="auto"==O?Math.max(k.outerHeight(!1),k.height()):parseInt(O,10);N=Q;V=R+S;u?N=T-E-D:C<G&&Math.max(C,0)+z>G||"bottomTop"==q.positionBy?Q+E+D>V&&T-R>E+D?(N=T-E-D,f="top"):(N=T+D,f="bottom"):N=Q+E+D>V?E>=S?R:V-E-D:"block"==n.css("display")||"area"==s.tagName.toLowerCase()?c-D:Q-q.dropShadowSteps;""==f&&(C<F?f="left":f="right");k.css({top:N+"px"}).removeClass().addClass("clue-"+f+"-"+P).addClass(P);q.arrows?(c=Q-N-q.dropShadowSteps,m.css({top:/(left|right)/.test(f)&&0<=
C&&0<c?c+"px":/(left|right)/.test(f)?0:""}).show()):m.hide();r.hide();k.hide()[q.fx.open](q.fx.openSpeed||0);q.dropShadow&&r.css({height:E,width:M,zIndex:n.data("thisInfo").zIndex-1}).show();b.fn.bgiframe&&k.bgiframe()},W=function(){g.parent().hide().removeClass();e.empty();l.empty();n.removeClass("cluetip-clicked");H&&n.attr(q.titleAttribute,H);n.css("cursor","");q.arrows&&m.css({top:""})};b(document).bind("hideCluetip",function(){W()});n[q.clickThrough?"unbind":"bind"]("click",function(){return!1});
n.bind("mouseenter.cluetip",function(g){k.removeClass();0<M&&k.css({width:M});J==n.attr("href")&&n.css("cursor","help");q.hoverClass&&n.addClass(q.hoverClass);Q=n.children().length?n.children().offset().top:n.offset().top;F=n.offset().left;G=g.pageX;T=g.pageY;"area"!=s.tagName.toLowerCase()&&(R=b(document).scrollTop(),L=b(window).width());C=u?F+5:K>F&&F>z&&0<z||F+K+z+I>L?F-z-I:K+F+I;if("area"==s.tagName.toLowerCase()||K+z>L)G+20+z>L?(k.addClass(P),C=0<=G-z-I?G-z-I-parseInt(k.css("marginLeft"),10)+
parseInt(e.css("marginRight"),10):G-z/2):C=G+I;var f=0>C?g.pageY+D:g.pageY;k.css({left:0<C&&"bottomTop"!=q.positionBy?C:G+z/2>L?L/2-z/2:Math.max(G-z/2,0),zIndex:n.data("thisInfo").zIndex});m.css({zIndex:n.data("thisInfo").zIndex+1});S=b(window).height();c?("function"==typeof c&&(c=c.call(s)),e.html(c),0<q.tipDelay?setTimeout(function(){X(f)},q.tipDelay):X(f)):U&&(e.html(U.length?U[0]:""),0<q.tipDelay?setTimeout(function(){X(f)},q.tipDelay):X(f));if(q.fixed){var l=C-g.pageX,r=N?N-g.pageY:Q-g.pageY;
n.bind("mousemove.cluetip",function(b){k.css({left:b.pageX+l,top:b.pageY+r})})}}).bind("mouseleave.cluetip",function(){(!q.sticky||/click|toggle/.test("hover"))&&W();q.hoverClass&&n.removeClass(q.hoverClass);n.unbind("mousemove.cluetip")});n.bind("mouseover.cluetip",function(){n.attr("title","")}).bind("mouseleave.cluetip",function(){n.attr("title",n.data("thisInfo").title)})})}})(jQuery);
(function(b){var c=function(c,k){var e=b.extend({},b.fn.nivoSlider.defaults,k),g={currentSlide:0,currentImage:"",totalSlides:0,running:!1,paused:!1,stop:!1,controlNavEl:!1,hideCap:!1},l=b(c);l.data("nivo:vars",g).addClass("nivoSlider");l.css("position","relative");b(".nivoSlider img").css({position:"absolute",top:0,left:0});var m=l.children();m.each(function(){var c=b(this),e="";c.is("img")||(c.is("a")&&(c.addClass("nivo-imageLink"),e=c),c=c.find("img:first"));var k=0===k?c.attr("width"):c.width(),
f=0===f?c.attr("height"):c.height();""!==e&&e.css("display","none");c.css("display","none");g.totalSlides++});b(".nivoSlider a.nivo-imageLink").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",display:"none","z-index":60,opacity:0,background:"#fff"});e.randomStart&&(e.startSlide=Math.floor(Math.random()*g.totalSlides));0<e.startSlide&&(e.startSlide>=g.totalSlides&&(e.startSlide=g.totalSlides-1),g.currentSlide=e.startSlide);g.currentImage=b(m[g.currentSlide]).is("img")?b(m[g.currentSlide]):
b(m[g.currentSlide]).find("img:first");b(m[g.currentSlide]).is("a")&&b(m[g.currentSlide]).css("display","block");var r=b('<img class="nivo-main-image" src="#" />');r.attr("src",g.currentImage.attr("src")).show();l.append(r);b(window).resize(function(){e.scale&&l.children("img").width(l.width());r.attr("src",g.currentImage.attr("src"));r.stop().height("auto");b(".nivo-slice").remove();b(".nivo-box").remove()});l.append(b('<div class="nivo-caption"><p></p></div>').css({display:"none",position:"absolute",
"z-index":"89",opacity:e.captionOpacity}));-1E4<e.t&&b(".nivo-caption",l).css({top:e.t,left:e.l});var s=function(c){var e=b(".nivo-caption",l);if(""!=g.currentImage.attr("title")&&void 0!=g.currentImage.attr("title")){var k=g.currentImage.attr("title");"#"==k.substr(0,1)&&(k=b(k).html());p=k.indexOf("~");-1<p&&(title2=k.substr(p+1),k=k.substr(0,p)+"<br><span>"+title2+"</span>");"block"==e.css("display")?c.captionAni?b(".nivo-caption",l).fadeOut(c.animSpeed,function(){b(".nivo-caption p",l).html(k);
b(this).fadeIn(c.animSpeed)}):setTimeout(function(){b(".nivo-caption p",l).html(k)},c.animSpeed):(b(".nivo-caption p",l).html(k),e.stop().fadeIn(c.animSpeed))}else e.stop().fadeOut(c.animSpeed)};-1E4<e.t&&b(".nivo-caption",l).css({top:e.t,left:e.l});e.hideCap||s(e);var n=0;!e.manualAdvance&&1<m.length&&(n=setInterval(function(){A(l,m,e,!1)},e.pauseTime));e.directionNav&&(l.append('<div class="nivo-directionNav"><a class="nivo-prevNav">'+e.prevText+'</a><a class="nivo-nextNav">'+e.nextText+"</a></div>"),
e.directionNavHide&&(b(".nivo-directionNav",l).hide(),l.hover(function(){b(".nivo-directionNav",l).show()},function(){b(".nivo-directionNav",l).hide()})),b("a.nivo-prevNav",l).live("click",function(){if(g.running)return!1;clearInterval(n);n="";g.currentSlide-=2;A(l,m,e,"prev")}),b("a.nivo-nextNav",l).live("click",function(){if(g.running)return!1;clearInterval(n);n="";A(l,m,e,"next")}));if(e.controlNav){g.controlNavEl=b('<div class="nivo-controlNav"></div>');l.after('<div class="clear"></div>');l.after(g.controlNavEl);
for(var u=0;u<m.length;u++)if(e.controlNavThumbs){g.controlNavEl.addClass("nivo-thumbs-enabled");var q=m.eq(u);q.is("img")||(q=q.find("img:first"));q.attr("data-thumb")&&g.controlNavEl.append('<a class="nivo-control" rel="'+u+'"><img src="'+q.attr("data-thumb")+'" alt="" /></a>')}else g.controlNavEl.append('<a class="nivo-control" rel="'+u+'">'+(u+1)+"</a>");b("a:eq("+g.currentSlide+")",g.controlNavEl).addClass("active");b("a",g.controlNavEl).bind("click",function(){if(g.running||b(this).hasClass("active"))return!1;
clearInterval(n);n="";r.attr("src",g.currentImage.attr("src"));g.currentSlide=b(this).attr("rel")-1;A(l,m,e,"control")})}e.pauseOnHover&&l.hover(function(){g.paused=!0;clearInterval(n);n=""},function(){g.paused=!1;""===n&&!e.manualAdvance&&(n=setInterval(function(){A(l,m,e,!1)},e.pauseTime))});l.bind("nivo:animFinished",function(){r.attr("src",g.currentImage.attr("src"));g.running=!1;b(m).each(function(){b(this).is("a")&&b(this).css("display","none")});b(m[g.currentSlide]).is("a")&&b(m[g.currentSlide]).css("display",
"block");""===n&&(!g.paused&&!e.manualAdvance)&&(n=setInterval(function(){A(l,m,e,!1)},e.pauseTime));e.afterChange.call(this)});var v=function(c,e,g){b(g.currentImage).parent().is("a")&&b(g.currentImage).parent().css("display","block");b('img[src="'+g.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").width(e.scale?c.width():"").css("visibility","hidden").show();for(var k=b('img[src="'+g.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").parent().is("a")?
b('img[src="'+g.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").parent().height():b('img[src="'+g.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").height(),f=0;f<e.slices;f++){var m=Math.round(c.width()/e.slices);f===e.slices-1?c.append(b('<div class="nivo-slice" name="'+f+'"><img src="'+g.currentImage.attr("src")+'" style="position:absolute;'+(e.scale?"width:"+c.width()+"px;":"")+"height:auto; display:block !important; top:0; left:-"+(m+f*m-m)+
'px;" /></div>').css({left:m*f+"px",width:c.width()-m*f+"px",height:k+"px",opacity:"0",overflow:"hidden"})):c.append(b('<div class="nivo-slice" name="'+f+'"><img src="'+g.currentImage.attr("src")+'" style="position:absolute;'+(e.scale?" width:"+c.width()+"px;":"")+"height:auto; display:block !important; top:0; left:-"+(m+f*m-m)+'px;" /></div>').css({left:m*f+"px",width:m+"px",height:k+"px",opacity:"0",overflow:"hidden"}))}b(".nivo-slice",c).height(k);e.scale&&r.stop().animate({height:b(g.currentImage).height()},
e.animSpeed)},B=function(c,e,g){b(g.currentImage).parent().is("a")&&b(g.currentImage).parent().css("display","block");b('img[src="'+g.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").width(e.scale?c.width():"").css("visibility","hidden").show();for(var k=Math.round(c.width()/e.boxCols),f=Math.round(b('img[src="'+g.currentImage.attr("src")+'"]',c).not(".nivo-main-image,.nivo-control img").height()/e.boxRows),m=0;m<e.boxRows;m++)for(var l=0;l<e.boxCols;l++)l===e.boxCols-1?
c.append(b('<div class="nivo-box" name="'+l+'" rel="'+m+'"><img src="'+g.currentImage.attr("src")+'" style="position:absolute;'+(e.scale?"width:"+c.width()+"px;":"")+"height:auto; display:block; top:-"+f*m+"px; left:-"+k*l+'px;" /></div>').css({opacity:0,left:k*l+"px",top:f*m+"px",width:c.width()-k*l+"px"})):c.append(b('<div class="nivo-box" name="'+l+'" rel="'+m+'"><img src="'+g.currentImage.attr("src")+'" style="position:absolute;'+(e.scale?"width:"+c.width()+"px;":"")+"height:auto; display:block; top:-"+
f*m+"px; left:-"+k*l+'px;" /></div>').css({opacity:0,left:k*l+"px",top:f*m+"px",width:k+"px"})),b('.nivo-box[name="'+l+'"]',c).height(b('.nivo-box[name="'+l+'"] img',c).height()+"px");e.scale&&r.stop().animate({height:b(g.currentImage).height()},e.animSpeed)},A=function(c,e,g,k){var f=c.data("nivo:vars");f&&f.currentSlide===f.totalSlides-1&&g.lastSlide.call(this);if((!f||f.stop)&&!k)return!1;g.beforeChange.call(this);k?("prev"===k&&r.attr("src",f.currentImage.attr("src")),"next"===k&&r.attr("src",
f.currentImage.attr("src"))):r.attr("src",f.currentImage.attr("src"));f.currentSlide++;f.currentSlide===f.totalSlides&&(f.currentSlide=0,g.slideshowEnd.call(this));0>f.currentSlide&&(f.currentSlide=f.totalSlides-1);f.currentImage=b(e[f.currentSlide]).is("img")?b(e[f.currentSlide]):b(e[f.currentSlide]).find("img:first");g.controlNav&&(b("a",f.controlNavEl).removeClass("active"),b("a:eq("+f.currentSlide+")",f.controlNavEl).addClass("active"));g.hideCap||s(g);b(".nivo-slice",c).remove();b(".nivo-box",
c).remove();var m=g.effect;k="";"random"===g.effect&&(k="sliceDownRight sliceDownLeft sliceUpRight sliceUpLeft sliceUpDown sliceUpDownLeft fold fade boxRandom boxRain boxRainReverse boxRainGrow boxRainGrowReverse slideInRight slideInLeft pushLeft".split(" "),m=k[Math.floor(Math.random()*(k.length+1))],void 0===m&&(m="fade"));-1!==g.effect.indexOf(",")&&(k=g.effect.split(","),m=k[Math.floor(Math.random()*k.length)],void 0===m&&(m="fade"));f.currentImage.attr("data-transition")&&(m=f.currentImage.attr("data-transition"));
f.running=!0;var l=0,n=0,q=k="",u="";k="";if("sliceDown"===m||"sliceDownRight"===m||"sliceDownLeft"===m)v(c,g,f),n=l=0,k=b(".nivo-slice",c),"sliceDownLeft"===m&&(k=b(".nivo-slice",c)._reverse()),k.each(function(){var e=b(this);e.css({top:"0px"});n===g.slices-1?setTimeout(function(){e.animate({opacity:"1.0"},g.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+l):setTimeout(function(){e.animate({opacity:"1.0"},g.animSpeed)},100+l);l+=50;n++});else if("sliceUp"===m||"sliceUpRight"===m||"sliceUpLeft"===
m)v(c,g,f),n=l=0,k=b(".nivo-slice",c),"sliceUpLeft"===m&&(k=b(".nivo-slice",c)._reverse()),k.each(function(){var e=b(this);e.css({bottom:"0px"});n===g.slices-1?setTimeout(function(){e.animate({opacity:"1.0"},g.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+l):setTimeout(function(){e.animate({opacity:"1.0"},g.animSpeed)},100+l);l+=50;n++});else if("sliceUpDown"===m||"sliceUpDownRight"===m||"sliceUpDownLeft"===m){v(c,g,f);var A=n=l=0;k=b(".nivo-slice",c);"sliceUpDownLeft"===m&&(k=b(".nivo-slice",
c)._reverse());k.each(function(){var e=b(this);0===n?(e.css("top","0px"),n++):(e.css("bottom","0px"),n=0);A===g.slices-1?setTimeout(function(){e.animate({opacity:"1.0"},g.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+l):setTimeout(function(){e.animate({opacity:"1.0"},g.animSpeed)},100+l);l+=50;A++})}else if("fold"===m)v(c,g,f),n=l=0,b(".nivo-slice",c).each(function(){var e=b(this),f=e.width();e.css({top:"0px",width:"0px"});n===g.slices-1?setTimeout(function(){e.animate({width:f,opacity:"1.0"},
g.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+l):setTimeout(function(){e.animate({width:f,opacity:"1.0"},g.animSpeed)},100+l);l+=50;n++});else if("fade"===m)v(c,g,f),q=b(".nivo-slice:first",c),q.css({width:c.width()+"px"}),q.animate({opacity:"1.0"},2*g.animSpeed,"",function(){c.trigger("nivo:animFinished")});else if("slideInRight"===m)v(c,g,f),q=b(".nivo-slice:first",c),q.css({width:"0px",opacity:"1"}),q.animate({width:c.width()+"px"},2*g.animSpeed,"",function(){c.trigger("nivo:animFinished")});
else if("slideInLeft"===m)v(c,g,f),q=b(".nivo-slice:first",c),q.css({width:"0px",opacity:"1",left:"",right:"0px"}),q.animate({width:c.width()+"px"},2*g.animSpeed,"",function(){q.css({left:"0px",right:""});c.trigger("nivo:animFinished")});else if("pushLeft"==g.effect){b(".nivo-main-image",c).css("visibility","hidden");b(".nivo-imageLink",c).css({opacity:"1.0"});var l=n=0,J=c.width(),M,z,K,F;prev_slide=0==f.currentSlide?f.totalSlides-1:f.currentSlide-1;K=b(e[prev_slide]);M=K.is("img")?K:K.children();
F=b(e[f.currentSlide]);z=F.is("img")?F:F.children();null!=z&&z.css({display:"block"});F.css({left:J,display:"block"});K.css({left:0,display:"block"});null!=M&&M.css({display:"block"});K.animate({left:"-"+J},{step:function(b,c){"left"==c.prop&&(percentDone=0===c.end-c.start?0:(c.now-c.start)/(c.end-c.start));F.css({left:J-percentDone*J+"px"})},duration:2*g.animSpeed,complete:function(){null!=M&&M.css({display:"none"});K.css({display:"none",left:0});b(".nivo-slice",c).css({opacity:"1.0"});c.trigger("nivo:animFinished")}})}else if("boxRandom"===
m){B(c,g,f);u=g.boxCols*g.boxRows;l=n=0;e=b(".nivo-box",c);for(var C,f=e.length;f;z=parseInt(Math.random()*f,10),C=e[--f],e[f]=e[z],e[z]=C);e.each(function(){var e=b(this);n===u-1?setTimeout(function(){e.animate({opacity:"1"},g.animSpeed,"",function(){c.trigger("nivo:animFinished")})},100+l):setTimeout(function(){e.animate({opacity:"1"},g.animSpeed)},100+l);l+=20;n++})}else if("boxRain"===m||"boxRainReverse"===m||"boxRainGrow"===m||"boxRainGrowReverse"===m){B(c,g,f);var u=g.boxCols*g.boxRows,G=l=
n=0,L=0,H=[];H[G]=[];k=b(".nivo-box",c);if("boxRainReverse"===m||"boxRainGrowReverse"===m)k=b(".nivo-box",c)._reverse();k.each(function(){H[G][L]=b(this);L++;L===g.boxCols&&(G++,L=0,H[G]=[])});for(z=0;z<2*g.boxCols;z++){C=z;for(e=0;e<g.boxRows;e++)0<=C&&C<g.boxCols&&(function(e,f,k,l,n){var q=b(H[e][f]),r=q.width(),s=q.height();("boxRainGrow"===m||"boxRainGrowReverse"===m)&&q.width(0).height(0);l===n-1?setTimeout(function(){q.animate({opacity:"1",width:r,height:s},g.animSpeed/1.3,"",function(){c.trigger("nivo:animFinished")})},
100+k):setTimeout(function(){q.animate({opacity:"1",width:r,height:s},g.animSpeed/1.3)},100+k)}(e,C,l,n,u),n++),C--;l+=100}}},J=function(b){this.console&&"undefined"!==typeof console.log&&console.log(b)};this.stop=function(){b(c).data("nivo:vars").stop||(b(c).data("nivo:vars").stop=!0,J("Stop Slider"))};this.start=function(){b(c).data("nivo:vars").stop&&(b(c).data("nivo:vars").stop=!1,J("Start Slider"))};e.afterLoad.call(this);return this};b.fn.nivoSlider=function(f){return this.each(function(){var k=
b(this);if(k.data("nivoslider"))return k.data("nivoslider");var e=new c(this,f);k.data("nivoslider",e)})};b.fn.nivoSlider.defaults={effect:"random",slices:15,boxCols:8,boxRows:4,t:-1E4,l:-1E4,animSpeed:1E3,pauseTime:3E3,startSlide:0,scale:!0,directionNav:!0,directionNavHide:!0,controlNav:!1,controlNavThumbs:!1,pauseOnHover:!0,manualAdvance:!1,prevText:"Prev",nextText:"Next",captionOpacity:0.8,captionAni:!1,randomStart:!1,beforeChange:function(){},afterChange:function(){},slideshowEnd:function(){},
lastSlide:function(){},afterLoad:function(){}};b.fn._reverse=[].reverse})(jQuery);
jQuery.SmoothScroll=function(b){function c(b){return b.replace(/^\//,"").replace(/(index|default).[a-zA-Z]{3,4}$/,"").replace(/\/$/,"")}var f=c(location.pathname),k=function(b){for(var c=0,f=arguments.length;c<f;c++){var k=arguments[c],r=$(k);if(0<r.scrollTop())return k;r.scrollTop(1);var s=0<r.scrollTop();r.scrollTop(0);if(s)return k}return[]}("html","body");$("a[href*=#]").each(function(){var e=c(this.pathname)||f;if(f==e&&(location.hostname==this.hostname||!this.hostname)&&this.hash.replace(/#/,
"")){var e=$(this.hash),g=this.hash;if(g){var l=e.offset().top;$(this).click(function(c){c.preventDefault();$(k).animate({scrollTop:l},b,function(){location.hash=g})})}}})};
$.fn.extend({reflect:function(b){b=$.extend({height:0.165,opacity:0.5},b);return this.unreflect().each(function(){var c=this;if(/^img$/i.test(c.tagName)){var f=function(){var f=c.width,e=c.height,g,l,m,r;l=Math.floor(1<b.height?Math.min(e,b.height):e*b.height);g=$("<canvas />")[0];if(g.getContext){m=g.getContext("2d");try{$(g).attr({width:f,height:l}),m.save(),m.translate(0,e-1),m.scale(1,-1),m.drawImage(c,0,0,f,e),m.restore(),m.globalCompositeOperation="destination-out",r=m.createLinearGradient(0,
0,0,l),r.addColorStop(0,"rgba(255, 255, 255, "+(1-b.opacity)+")"),r.addColorStop(1,"rgba(255, 255, 255, 1.0)"),m.fillStyle=r,m.rect(0,0,f,l),m.fill()}catch(s){return}}else{if(!$.browser.msie)return;g=$("<img />").attr("src",c.src).css({width:f,height:e,marginBottom:l-e,filter:"FlipV progid:DXImageTransform.Microsoft.Alpha(Opacity="+100*b.opacity+", FinishOpacity=0, Style=1, StartX=0, StartY=0, FinishX=0, FinishY="+100*(l/e)+")"})[0]}$(g).css({display:"block",border:0});g=$(/^a$/i.test(c.parentNode.tagName)?
"<span />":"<div />").insertAfter(c).append([c,g])[0];g.className=c.className;$.data(c,"reflected",g.style.cssText=c.style.cssText);$(g).css({width:f,height:e+l,overflow:"hidden"});c.style.cssText="display: block; border: 0px";c.className="reflected"};c.complete?f():$(c).load(f)}})},unreflect:function(){return this.unbind("load").each(function(){var b=$.data(this,"reflected"),c;void 0!==b&&(c=this.parentNode,this.className=c.className,this.style.cssText=b,$.removeData(this,"reflected"),c.parentNode.replaceChild(this,
c))})}});
(function(b){b.fn.livesearch=function(){function c(){""==b.trim(searcher.val())||4>b.trim(searcher.val()).length?b("#pre-search-content").html("").hide():b.ajax({url:searcher.parent("form").attr("action")+"?q="+searcher.val()+"&action=search&x=1"}).done(function(c){b("#pre-search-content").html(c).show()})}searcher=b(this);searcher.attr("autocomplete","off");searcher.parent("form").parent().append('<div id="pre-search-content" style="width: '+searcher.parent("form").width()+'px; background: white; display: none;"></div>');var f,
k=!1;searcher.keyup(function(){f=setTimeout(c,1E3)});searcher.keydown(function(){clearTimeout(f)});searcher.blur(function(){k||b("#pre-search-content").hide()});searcher.focus(function(){b("#pre-search-content").show()});b("#pre-search-content").hover(function(){k=!0},function(){k=!1})}})(jQuery);
(function(b){b.fn.easyAccordion=function(c){var f={autoStart:!1,slideInterval:3E3};this.each(function(){var k=b.extend(f,c);$(this).find("dl").addClass("easy-accordion");b.fn.setVariables=function(){dlWidth=$(this).width();dlHeight=$(this).height();dtWidth=$(this).find("dt").outerWidth(!1);b.browser.msie&&(dtWidth=$(this).find("dt").outerWidth(!1));dtHeight=$(this).find("dt").width();slideTotal=$(this).find("dt").size();ddWidth=dlWidth-dtWidth*slideTotal-($(this).find("dd").outerWidth(!0)-$(this).find("dd").width());
ddHeight=dlHeight-($(this).find("dd").outerHeight(!0)-$(this).find("dd").height())};$(this).setVariables();$(this).find("dt").each(function(){$(this).css({width:dtHeight,top:0,"margin-left":0})});$(this).find(".active").size()?$(this).find(".active").next("dd").addClass("active"):$(this).find("dt:first").addClass("active").next("dd").addClass("active");$(this).find("dt:first").css({left:"0"}).next().css({left:dtWidth});$(this).find("dd").css({width:ddWidth,height:ddHeight});b.fn.findActiveSlide=function(){var b=
1;this.find("dt").each(function(){$(this).hasClass("active")?activeID=b:$(this).hasClass("no-more-active")&&(noMoreActiveID=b);b+=1})};b.fn.calculateSlidePos=function(){var c=2;$(this).find("dt").not(":first").each(function(){var b=dtWidth*activeID;if(c<=activeID){var e=dtWidth*(c-1);$(this).animate({left:e});c<activeID?$(this).next().css({left:e+dtWidth}):$(this).next().animate({left:b})}else b=dlWidth-dtWidth*(slideTotal-c+1),$(this).animate({left:b}),b+=dtWidth,$(this).next().animate({left:b});
c+=1});setTimeout(function(){b(".easy-accordion").find("dd").not(".active").each(function(){$(this).css({display:"none"})})},400)};b.fn.activateSlide=function(){this.parent("dl").setVariables();this.parent("dl").find("dd").css({display:"block"});this.parent("dl").find("dd.plus").removeClass("plus");this.parent("dl").find(".no-more-active").removeClass("no-more-active");this.parent("dl").find(".active").removeClass("active").addClass("no-more-active");this.addClass("active").next().addClass("active");
this.parent("dl").findActiveSlide();activeID<noMoreActiveID&&this.parent("dl").find("dd.no-more-active").addClass("plus");this.parent("dl").calculateSlidePos()};b.fn.rotateSlides=function(b,c){var e=$(this);c.value=setTimeout(function(){e.rotateSlides(b,c)},b);$(this).findActiveSlide();var g=$(this).find("dt").size(),f=activeID+1;f>g&&(f=1);$(this).find("dt:eq("+(f-1)+")").activateSlide()};var e=new function(){this.value=null};$(this).findActiveSlide();$(this).calculateSlidePos();if(!0==k.autoStart){var g=
$(this),l=parseInt(k.slideInterval);e.value=setTimeout(function(){g.rotateSlides(l,e)},l)}$(this).find("dt").not("active").click(function(){$(this).activateSlide();clearTimeout(e.value)});b.browser.msie&&6==b.browser.version||b("dt").hover(function(){$(this).addClass("hover")},function(){$(this).removeClass("hover")})})}})(jQuery);
(function(b){b.fn.utils_frmvalidate=function(b,f,k,e,g,l,m,r){return this.each(function(){var s=$(this),n=$(this).attr("id");l&&($(s).parent().after('<iframe name="dummy" style="display:none">'),$(s).attr("target","dummy"));s.prepend('<input type="hidden" class="cc" name="cc" value="1"/>');var u=""==document.referrer?window.location.href:document.referrer,q=$("#"+n+" :input[name=message]");q.length&&$("#"+n+" :input[name=message]").val(q.val().replace("%URL%",u));s.submit(function(l){s=$(this);n=
$(this).attr("id");l.preventDefault();m?($(".frmhint").remove(),$("#"+n+" .inputerror").removeClass("inputerror")):($(".frmhint").empty(),$("#"+n+" .input1").removeClass("inputerror"));k&&$("#div_"+n).addClass("ajl").css("opacity","0.2").delay(500);var q="";f&&$(":file").each(function(){q+="&up_"+$(this).attr("name")+"="+$(this).val()});$.post(s.attr("action"),s.serialize()+q,function(f){k&&$("#div_"+n).removeClass("ajl").css("opacity","1");if("1"==f.charAt(0))f=$("#"+n+" .cc"),f.val("0"),s.unbind("submit"),
void 0!=r?r(s):s.submit(),f.val("1");else if("0"==f.charAt(0)){f=f.substring(1).split("|");for(i=0;i<f.length;i+=2)if(e){var l=$();g&&(l=$("#"+n+" *[name="+f[i]+"]").addClass("inputerror").parents("li:first"));l.length||(l=$("#"+n+" .ffooter"));$(l).append('<p class="rvts12 frmhint">'+f[i+1]+"</p>")}else $("#"+n+"_"+f[i]).append("<br />"+f[i+1]),$("#"+n+" input[name="+f[i]+"]").addClass("inputerror");b&&"function"==typeof reloadReCaptcha&&reloadReCaptcha()}else $("#div_"+n).length?$("#div_"+n).html(f):
$("#"+n+"_error").length&&$("#"+n+"_error").html(f)})})})}})(jQuery);function addfav(b,c){""==b&&(b=location.href);""==c&&(c=document.title);-1!=navigator.userAgent.toLowerCase().indexOf("opera")?alert("Press CTRL-T to add this page to favorites"):document.all?window.external.AddFavorite(b,c):window.sidebar&&window.sidebar.addPanel(c,b,"")}var ie=-1!=navigator.appName.indexOf("Microsoft");function unblend(b){co=b;hv=setInterval("hl(co)",40)}
function blend(b){clearInterval(hv);ie?b.filters.alpha.opacity=20:b.style.opacity&&(b.style.opacity=0.2)}function hl(b){ie&&100>b.filters.alpha.opacity?b.filters.alpha.opacity+=5:!ie&&1>b.style.opacity?b.style.opacity=parseFloat(b.style.opacity)+0.05:window.hv&&clearInterval(hv)}
function openhtml(b,c,f,k,e,g,l,m,r,s,n){if(0>s||0>n)n=Math.round((screen.availWidth-m)/2),s=Math.round((screen.availHeight-r)/2)-25;aw=window.open(b,"_blank","toolbar="+l+",menubar="+f+",scrollbars="+e+",resizable="+k+",status="+g+",location="+c+",width="+m+",height="+r+",top="+s+",left="+n);aw.opener=self;aw.focus();return!1}
function openpic(b,c,f,k,e,g,l,m,r,s,n,u,q){if(0>u||0>q)q=Math.round((screen.availWidth-s)/2),u=Math.round((screen.availHeight-n)/2)-25;aw=window.open("","","toolbar="+m+",menubar="+k+",scrollbars="+g+",resizable="+e+",status="+l+",location="+f+",width="+s+",height="+n+",top="+u+",left="+q);temp="<html><head><title>"+b+'</title></head><body style="margin:0;padding:0"><table cellspacing="0" cellpadding="0" style="width:100%;height:100%;background:#FFFFFF"><tr><td width="100%"><p class="rvps1"><a href="javascript:window.close();"><img width="'+
s+'" src="'+c+'"></a>';temp+="</td></tr></table></body></HTML>";aw.document.write(temp);0!=r&&aw.setTimeout("window.close()",r)}var ns6=document.getElementById&&!document.all,ie=document.all,prev_color;
function rollover_on(b,c,f,k,e,g){el=ie?event.srcElement:b.target;if("TABLE"!=el.tagName){for(;el&&"undefined"==typeof el.cellIndex;)el=ie?el.parentElement:el=el.parentNode;if(el&&"TABLE"!=el.tagName){if(ie||el.parentNode.cells[1]&&1==el.parentNode.cells[1].cellIndex)ci=el.cellIndex;else{myCells=el.parentNode.cells;for(j=0;j<myCells.length;j++)el==myCells[j]&&(ci=j)}if("TC"==f||"TRTC"==f)if(0<ci||""==e){g.ci=ci;for(x=fc=""==k?0:1;x<g.rows.length;x++)prev_color=g.rows[x].cells[ci].style.backgroundColor,
g.rows[x].cells[ci].style.backgroundColor=c}el=ie?event.srcElement:b.target;if("TABLE"!=el.tagName){for(;"TR"!=el.tagName&&"HTML"!=el.tagName;)el=ns6?el.parentNode:el.parentElement;ri=el.rowIndex;if("TRTC"==f||"TR"==f){if(""==k||0<ri){g.ri=ri;for(x=fc=""==e?0:1;x<g.rows[ri].cells.length;x++)"TR"==f&&c!=g.rows[ri].cells[x].style.backgroundColor&&(prev_color=g.rows[ri].cells[x].style.backgroundColor),g.rows[ri].cells[x].style.backgroundColor=c}}else if("TD"==f&&(""==k||0<ri)&&(""==e||0<ci))g.ri=ri,
g.ci=ci,prev_color=g.rows[ri].cells[ci].style.backgroundColor,g.rows[ri].cells[ci].style.backgroundColor=c}}}}
function rollover_off(b,c,f,k,e,g){if("TC"==f||"TRTC"==f)if(0<g.ci||""==e)for(x=fc=""==k?0:1;x<g.rows.length;x++)g.rows[x].cells[g.ci].style.backgroundColor=prev_color;if(("TRTC"==f||"TR"==f)&&g.rows[g.ri])for(x=fc=""==e?0:1;x<g.rows[g.ri].cells.length;x++)g.rows[g.ri].cells[x].style.backgroundColor=prev_color;"TD"==f&&g.rows[g.ri]&&(g.rows[g.ri].cells[g.ci].style.backgroundColor=prev_color)}
function MultiSelector(b){this.list_target=b;this.id=this.count=0;this.addElement=function(b){"INPUT"==b.tagName&&"file"==b.type?(b.name="file_"+this.id++,b.multi_selector=this,b.onchange=function(){var b=document.createElement("input");b.type="file";this.parentNode.insertBefore(b,this);this.multi_selector.addElement(b);this.multi_selector.addListRow(this);this.style.position="absolute";this.style.left="-1000px"},this.count++,this.current_element=b):alert("Error")};this.addListRow=function(b){var f=
document.createElement("p"),k=document.createElement("input");k.type="button";k.value="Delete ("+b.value+")";k.className="button medium";f.element=b;k.onclick=function(){this.parentNode.element.parentNode.removeChild(this.parentNode.element);this.parentNode.parentNode.removeChild(this.parentNode);this.parentNode.element.multi_selector.count--;return this.parentNode.element.multi_selector.current_element.disabled=!1};f.appendChild(k);this.list_target.appendChild(f)}}var b_el=null,tog=!1;
function ToggleBody(b,c){tog&&(null!=b_el&&b_el!=b)&&($("#"+b_el+"Body").slideUp(),$("#"+b_el+"Up").attr("src",c+"images/expand.gif"));$("#"+b+"Body").slideToggle(function(){b_el=b;src="block"==$(this).css("display")?"collapse":"expand";img=c+"images/"+src+".gif";$("#"+b+"Up").attr("src",img)});return!1}var hda="",opa;
function initLogin(b,c){if(0==$("#"+b).length)return!1;$("#"+b).bind("mousedown",function(b){b.stopPropagation()});c&&$(document).bind("mousedown",function(b){""!=hda&&b.pageX<$(window).width()-15&&hide_Hdiv(hda)})}
function show_Hdiv(b,c,f,k,e,g,l){if(1==(null==l?0:l))if(ck=$.cookie("hdiv"),null==ck&&(ck=""),-1==ck.indexOf("|"+b+"|"))$.cookie("hdiv",ck+"|"+b+"|",1);else return;hda=b;opa=null==k?1:k;pos=null==e?0:e;g=null==g?0:g;w=$(window).width();h=$(window).height();st=0==g?$(window).scrollTop():0;dw=$("#"+b).width();dh=$("#"+b).height();1==pos?$("#"+b).css({left:(w-dw)/2,top:(h-dh)/2+st}):2==pos?$("#"+b).css({left:5,top:5+st}):3==pos?$("#"+b).css({left:w-dw-40,top:5+st}):4==pos?$("#"+b).css({left:5,top:h-
dh-45+st}):5==pos&&$("#"+b).css({left:w-dw-40,top:h-dh-45+st});1==g&&$("#"+b).css({position:"fixed"});$("#"+b).fadeIn(c);!1!=f&&(null!=f?$("#"+b).draggable({handle:"handle"}):$("#"+b).draggable())}function hide_Hdiv(b){hda="";$("#"+b).fadeOut(500)}function sClo(){$(".bkf_h").hide()}function sCls(){"undefined"!=typeof t&&clearTimeout(t)}function sTim(){t=setTimeout(sClo,1E3)}
function getImages(b,c){filter="img:not(.sb_img,.bullet,.cim,.bullet,.system_img)";obj=$(c).parents(".post_wrap").length?$(c).parents(".post_wrap").find(filter):$("#xm2 "+filter);obj.each(function(){60>$(this).width()||40>$(this).height()||(src=$(this)[0].src,url=b.replace("%MEDIA%",src),$(".sb_ul").append('<li><div class="img_block"><a href="'+url+'" target="_blank"><img class="sbp_img" src="'+src+'"/></a></div></li>'))})}
$(document).ready(function(){$(".bkc").hover(function(){bkf=$(this).children(".bkf");h=$(this).height();w=$(this).width();bw=$(bkf).width();winPos=$(window).scrollTop()+$(window).height();elPos=$(this).offset().top+h+$(bkf).height();$(bkf).css("top",winPos<elPos?"-"+$(bkf).height()+"px":h);winPos=$(window).scrollLeft()+$(window).width();elPos=$(this).offset().left+bw;$(bkf).css("left",winPos<elPos?"-"+(bw-w)+"px":0);$(bkf).show()},function(){sTim()});$(".bkf").hover(function(){sCls()},function(){sTim()});
$(".sb_pinterest").each(function(){$(this).click(function(b){$("body").append('<div class="sb_images"><img src="http://www.ezgenerator.com/social/pinterest.png"><a onclick="$(this).parent().remove();" class="close_btn"> X </a><ul class="sb_ul"></ul></div>');b.preventDefault();getImages($(this).attr("href"),this);$(".sb_images").css("top",($(window).height()-470)/2).show("fast")})})});
function loadCaptcha(b){var c=new Date;$("<img />").attr({src:b+"ezg_data/captcha.php?"+c.getTime(),"class":"system_img"}).load(function(){$("span.captcha").append($(this).clone(!0).unbind("load"));$(this).unbind("load");$("span.captcha img").click(function(){$("span.captcha").empty();loadCaptcha(b)})})};